print('#'*4+'PARABENS'+'#'*4)
print('Olha o Dinossauro:')
print('            __')
print('           / _)')
print('    ._^^^_/ /')
print(' __/       /')
print('<__.|_|-|_|')
print('Olha o Bolo:')
print('ii'*10)
print('#'*20)
print('='*20)
print('#'*20)
print('='*20)