print('O que eu mais gosto de fazer é jogar:')
print(' O')
print(' |')
print(' |')
print('___')
print('| |')
print('___')

print('Eu moro em Teresina:')
print(' _|_')
print('|*  |')
print('|  *|_____')
print('|   |     |')
print('|   |    *|')
print('|   |     |')